#!/system/bin/sh
#================================
# MAGISK ALIAS'
#================================
alias wget="/sbin/.core/busybox/wget"
#================================
# VARIABLES
#================================
if [ -d /system/xbin ]; then
    bin=xbin
else
    bin=bin
fi
. /system/$bin/mc_init
MIDFONT="/sdcard/MidnightMain/MidnightFonts"
STOREFONT="$MIDFONT/tmp_fonts"
FONTBACKUP="$MIDFONT/Backup"
if [ -f "$MIDFONT/currently_applied_font.txt" ]; then
    CURRENT=$G"$( cat $MIDFONT/currently_applied_font.txt )"$N
else
    CURRENT=$R"Default"$N
fi
#================================
# ENVIRONMENT SETUP
#================================
mkdir -p $STOREFONT > /dev/null 2>&1
mkdir -p $FONTBACKUP > /dev/null 2>&1
echo "[+] Setting Up Environment..."
wget --no-check-certificate -q -O $STOREFONT/font-list "https://ncloud.zaclys.com/index.php/s/jWG7VgSePf30Dat/download"
if [ $? != 0 ]; then
    show_error "Fonts List not downloaded." "Bad Internet Connection." "Check your internet connection. Remove any active VPN(s)."
	sleep 2
fi
echo "[+] Fonts list downloaded to: $STOREFONT !"
wget --no-check-certificate -q -O $STOREFONT/font-link-list "https://ncloud.zaclys.com/index.php/s/HQpbpeNKYp5crlz/download"
if [ $? != 0 ]; then
    show_error "Fonts List not downloaded." "Bad Internet Connection." "Check your internet connection. Remove any active VPN(s)."
	sleep 2
fi
echo "[+] Links list downloaded to: $STOREFONT !"
sleep 2
#================================
#================================
main=true
. $fonts_backend
while [ "$main" == true ]
do
    clear
    echo -e $Y"$divider"$N
    echo -e $G"          _____ ____    _  ________________    "$N
    echo -e $G"         / ___//    \  / \/ /__   __//  __/    "$N
    echo -e $G"        / /__ / /__  \/    /  /  /  /__ \      "$N
    echo -e $G"       / ___/ \   /  /    /  /  /   __/  /     "$N
    echo -e $G"      /_/      \____/_/\_/  /__/   /____/      "$N
    echo -e $Y"$divider"$N
    echo -e $G"       A   M I D N I G H T   M O D U L E       "$N
    echo -e $Y"$divider"$N
    echo "             Applied: $CURRENT      "
    echo -e $Y"$divider"$N
    echo "[+] Choose From the selection of fonts offered below"
    echo "[+] Enter a corresponding Number"
    echo ""
    cat $STOREFONT/font-list
    echo ""
    echo "[q] Quit"
    echo ""
    echo -e -n $W"[CHOOSE]: "$N
    read -r INPUT
    case "$INPUT" in
        "$INPUT")
            if [ "$INPUT" == "q" ]; then
                main=false
            else
                LINK="$( cat $STOREFONT/font-link-list | xargs | cut -d '?' -f $INPUT | tr -d ' ' )"
                FONT="$( cat $STOREFONT/font-list | xargs | cut -d '.' -f $INPUT )"
                FONT2="$( echo $FONT | cut -d ']' -f 2 | tr -d ' ' )"
                check_stored
                font_steps
            fi
            ;;
    esac
done
